name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  basic:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build
        run: sudo chmod 777 docker-storage/entrypoint.sh |
          docker compose up -d
