name: docker-build
# This workflow represents a set of basic End-to-End tests
on:
  push:
  workflow_dispatch:

jobs:
  bulild-debug:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Docker build
        run: sudo chmod 777 docker-storage/entrypoint.sh |
          docker compose up

      - uses: actions/upload-artifact@v4
        with:
          name: bin-debug
          path: bin/
